#!/bin/bash
# ============================================================
# setup_sudoers.sh - Soop Mail privilege configuration
# Run ONCE on the server as root or with sudo:
#   sudo bash scripts/setup_sudoers.sh
# ============================================================

set -e

# Auto-detect the user running the soop_mail service
SOOP_USER=$(systemctl show -pUser soop_mail 2>/dev/null | cut -d= -f2)
if [ -z "$SOOP_USER" ]; then
    # Fallback: ask the user
    echo "Could not auto-detect service user. Enter the user running soop_mail (e.g. www-data, ubuntu):"
    read SOOP_USER
fi

echo "==> Configuring for user: $SOOP_USER"

# 1. Grant write access to /etc/postfix/vmailbox and /etc/dovecot/users
echo "==> Setting file ownership for Postfix and Dovecot config files..."
for FILE in /etc/postfix/vmailbox /etc/postfix/virtual /etc/postfix/sender_bcc /etc/postfix/recipient_bcc; do
    if [ -f "$FILE" ]; then
        chown root:$SOOP_USER "$FILE"
        chmod 664 "$FILE"
        echo "    OK: $FILE"
    else
        touch "$FILE"
        chown root:$SOOP_USER "$FILE"
        chmod 664 "$FILE"
        echo "    Created: $FILE"
    fi
done

if [ -f /etc/dovecot/users ]; then
    chown root:$SOOP_USER /etc/dovecot/users
    chmod 664 /etc/dovecot/users
    echo "    OK: /etc/dovecot/users"
fi

# 2. Grant access to mail directory
MAIL_DIRS="/var/mail/vhosts /var/mail/soop_mail /var/vmail"
for MAIL_DIR in $MAIL_DIRS; do
    if [ -d "$MAIL_DIR" ]; then
        echo "==> Granting access to mail directory $MAIL_DIR..."
        chown -R $SOOP_USER:$SOOP_USER "$MAIL_DIR"
        chmod -R 750 "$MAIL_DIR"
        echo "    OK: $MAIL_DIR"
    fi
done

# 3. Create sudoers file for postfix/dovecot commands
SUDOERS_FILE="/etc/sudoers.d/soop_mail"
echo "==> Creating sudoers file at $SUDOERS_FILE..."

cat > "$SUDOERS_FILE" << EOF
# Soop Mail - Allow service user to manage mail services without password
# Generated by setup_sudoers.sh

# Allow postmap (index postfix map files)
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/sbin/postmap

# Allow postfix reload/reload
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/sbin/postfix reload
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/sbin/postfix status
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl reload postfix
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart postfix

# Allow dovecot reload
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl reload dovecot
$SOOP_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart dovecot

# Allow chown on mail directories (for new mailbox creation)
$SOOP_USER ALL=(ALL) NOPASSWD: /bin/chown -R 5000\:5000 /var/mail/*
$SOOP_USER ALL=(ALL) NOPASSWD: /bin/chown -R vmail\:vmail /var/mail/*
$SOOP_USER ALL=(ALL) NOPASSWD: /bin/chmod -R 700 /var/mail/*
EOF

chmod 440 "$SUDOERS_FILE"

# 4. Validate the sudoers file
if visudo -cf "$SUDOERS_FILE"; then
    echo "    OK: Sudoers file is valid"
else
    echo "    ERROR: Sudoers file has syntax errors. Removing..."
    rm "$SUDOERS_FILE"
    exit 1
fi

# 5. Restart soop_mail service to pick up new permissions
echo "==> Restarting soop_mail service..."
systemctl restart soop_mail
echo "    OK: Service restarted"

echo ""
echo "============================="
echo " Setup complete!"
echo "============================="
echo " User '$SOOP_USER' can now:"
echo "  - Write to /etc/postfix/vmailbox"
echo "  - Run postmap and postfix reload"
echo "  - Reload dovecot"
echo "  - Set ownership of new mailboxes"
echo ""
echo " Test by creating a user in the dashboard."
echo "============================="


